params:
  bosh_env: &bosh_env
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))
  deployment: &deployment
    deployment: docker-swarm

jobs:
- name: test
  plan:
  - in_parallel:
    - get: stemcell
    - get: bosh-deployment
    - get: docker-release
    - get: xenial-ops-file
    - get: storage-driver-ops-file
  - put: cloud-config
    params:
      manifest: bosh-deployment/((bosh_cpi))/cloud-config.yml
      releases: []
  - put: deploy
    params:
      manifest: docker-release/manifests/swarm/docker-swarm.yml
      stemcells: [ stemcell/stemcell.tgz ]
      ops_files:
      - xenial-ops-file/ops.yml
      - storage-driver-ops-file/ops.yml

resources:
- name: xenial-ops-file
  type: file
  source:
    filename: ops.yml
    content:
    - type: replace
      path: /stemcells/alias=default/os
      value: ubuntu-xenial

- name: storage-driver-ops-file
  type: file
  source:
    filename: ops.yml
    content:
    - type: replace
      path: /instance_groups/name=docker/jobs/name=docker/properties/storage_driver?
      value: vfs

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    branch: master

- name: docker-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/docker-boshrelease.git
    branch: master

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: ((bosh_stemcell))

- name: deploy
  type: bosh-deployment
  source:
    <<: *deployment
    <<: *bosh_env

- name: cloud-config
  type: bosh-config
  source:
    config: cloud
    <<: *bosh_env

resource_types:
- name: bosh-config
  type: docker-image
  source:
    repository: cfcommunity/bosh-config-resource
    tag: edge

- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
    tag: latest

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest
