---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc
  - name: bosh-deployment

outputs:
  - name: bucc-out

run:
  path: bucc-ci/ci/tasks/get-latest-bosh-deployment/task
